"""HTTP contracts for the EDOCA demo API."""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field


class AnalyzeRequest(BaseModel):
	"""An engineer's consistency-assurance question."""

	query: str = Field(
		min_length=1,
		description="Engineering consistency or change-impact question.",
		examples=["Is there a consistency issue with Unit 400 Pass 1 temperature?"],
	)


class AnalyzeResponse(BaseModel):
	"""Complete, evidence-grounded output from the existing EDOCA workflow."""

	query: str = Field(description="The submitted engineering query.")
	intent: str = Field(description="Workflow-detected investigation intent.")
	retrieval_metadata: dict[str, Any] = Field(description="Hybrid retrieval mode and result metadata.")
	graph_context: dict[str, Any] = Field(description="Graph nodes, relationships, and linked documents.")
	evidence: list[dict[str, Any]] = Field(description="Retrieved source evidence chunks.")
	assurance_results: list[dict[str, Any]] = Field(description="Outputs from existing assurance engines.")
	findings: list[dict[str, Any]] = Field(description="Evidence-backed engineering findings.")
	recommendations: list[str] = Field(description="Distinct recommendations from the generated findings.")
	reasoning_output: dict[str, Any] = Field(description="Structured deterministic or GPT reasoning output.")
	executed_nodes: list[str] = Field(description="LangGraph nodes executed for this request.")
	errors: list[str] = Field(description="Captured workflow-node errors, if any.")


class FindingsResponse(BaseModel):
	"""The latest findings generated by the demo session."""

	findings: list[dict[str, Any]]


class FindingDetailResponse(BaseModel):
	"""One stored finding with its engineer-review history."""

	finding: dict[str, Any]


class ReviewFindingRequest(BaseModel):
	"""An engineer's lifecycle disposition for a finding."""

	status: Literal["OPEN", "REVIEW", "ACCEPTED", "REJECTED", "CLOSED"] = Field(
		description="New lifecycle status for the finding."
	)
	reviewer: str | None = Field(default=None, min_length=1, description="Engineer recording the review.")
	comment: str | None = Field(default=None, min_length=1, description="Optional review rationale.")


class AddCommentRequest(BaseModel):
	"""A review comment that does not change lifecycle status."""

	reviewer: str = Field(min_length=1, description="Engineer adding the comment.")
	comment: str = Field(min_length=1, description="Review note or rationale.")


class GraphResponse(BaseModel):
	"""Demo-ready graph context centered on an engineering entity."""

	requested_entity: str
	resolved_entity: dict[str, Any]
	nodes: list[dict[str, Any]]
	context_nodes: list[dict[str, Any]]
	context_included: bool
	relationships: list[dict[str, Any]]
	documents: list[str]
	related_findings: list[dict[str, Any]]


class ImpactAnalysisRequest(BaseModel):
	"""An entity selected for deterministic change-impact assessment."""

	entity: str = Field(min_length=1, examples=["R-401"])
	proposed_change: str = Field(
		min_length=1,
		description="Engineering change proposed for the selected entity.",
		examples=["Change setpoint from 620°C to 625°C"],
	)
	hops: int = Field(default=2, ge=0, le=3, description="Bounded deterministic graph traversal depth.")


class ImpactAnalysisResponse(BaseModel):
	"""Affected assets, documents, and graph radius for a proposed change."""

	entity: str
	proposed_change: str
	affected_assets: list[str]
	affected_documents: list[str]
	affected_relationships: list[dict[str, Any]]
	impact_radius: dict[str, Any]
	expanded_impact_radius: dict[str, Any]
	context_nodes: list[dict[str, Any]]
	assurance_results: list[dict[str, Any]]
	related_findings: list[dict[str, Any]]
	review_required: bool
